### ISSUE TITLE
spec suite creates after/before blocks globally

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-output-statsd#12]
because of https://github.com/logstash-plugins/logstash-output-statsd/blob/master/spec/spec_helper.rb#L56-L69, running tests of all plugins inside of logstash will fail some because these before/after blocks are set for every test, not just statsd output

This is why https://github.com/elastic/logstash/pull/3967#issuecomment-143186832 is happening

**Comment by ph** [comment]
good finding

**Comment by ph** [comment]
Fixed by #13
