### ISSUE TITLE
Increment is shipping values instead of incrementing

### ISSUE THREAD

**Issue by hpj1992** [logstash-plugins/logstash-output-statsd#21]
```
output
{

statsd
{

if ![%{abc}] {
increment => ["cpu.totalCount"]
}
if ![%{def}] {
increment => ["cpu.myCount"]
}

}
}

```
I want to measure how many time **abc** and **def** metrics were logged. Sample metric.
abc = 105
def = 334
abc = 23
abc = 45

As per documentation increment increases the count by 1 each time and flushes the value after 
interval.
I am getting values of metrics in **cpu.totalCount** and **cpu.myCount** rather than its occurrence count.

Am I doing anything wrong ? Is this correct behavior ?

**Comment by jordansissel** [comment]
Your logstash config seems to be invalid.. are you sure this is your configuration? This won't even run in logstash because it will show a syntax error in your config.

**Comment by jordansissel** [comment]
Can you help me understand more about what's going on? for example, I don't understand what you mean by "I am getting values of metrics in cpu.totalCount and cpu.myCount rather than its occurrence count."

Can you attach your logstash config?

**Comment by untergeek** [comment]
Let me show a format-edited version of your config above, then compare to what it probably should be, vis-a-vis @jordansissel's question about configuration:

```
output {
  statsd {
    if ![%{abc}] {
      increment => ["cpu.totalCount"]
    }
    if ![%{def}] {
      increment => ["cpu.myCount"]
    }
  }
}
```

The correct way to do conditionals is to have the entire plugin definition inside the conditional, like this:

```
output {
  if ![%{abc}] {
    statsd {
      increment => ["cpu.totalCount"]
    }
  }
  if ![%{def}] {
    statsd {
      increment => ["cpu.myCount"]
    }
  }
}
```

**Comment by untergeek** [comment]
Since this appears to be a configuration problem, rather than a code problem, I'm going to mark this as closed.  If you believe this is in error, please feel free to open a new ticket with more details.
